# Generated by Django 5.2 on 2025-08-11 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='demo_video'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
