[build]
nixpacksVersion = 1
languages = ["python"]
pythonVersion = "3.10"

[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "gcc",
  "libffi",
  "openssl",
  "pkg-config",
  "zlib"
]

[phases.install]
cmds = [
  "PIP_BREAK_SYSTEM_PACKAGES=1 pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
