[build]
nixpacksVersion = 1
languages = ["python", "nodejs"]
pythonVersion = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "ls",  # debugging step to show files
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
