[build]
nixpacksVersion = 1
languages = ["python"]
pythonVersion = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
