[phases.setup]
nixPkgs = ["python311Full", "gcc", "pkg-config"]

[phases.install]
cmds = ["python3 -m ensurepip", "python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput", "python3 manage.py migrate"]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
