[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput", "python3 manage.py migrate"]

[start]
cmd = "gunicorn backend.wsgi:application --workers 4"
