[build]
nixpacksVersion = 1
languages = ["python", "nodejs"]
pythonVersion = "3.10"  # ✅ safest for Django on Railway

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
