[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn backend.wsgi"
