[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[phases.start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
