[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
cmd = "gunicorn backend.wsgi:application --workers 4"
