[build]
nixpacksVersion = 1
languages = ["python"]
pythonVersion = "3.10"

[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "postgresql",
  "gcc",
  "libffi",
  "openssl",
  "pkg-config",
  "zlib",
]

[phases.install]
cmds = [
  "pip install --break-system-packages --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
