[setup]
nixPkgs = ["python311", "pip", "gcc"]

[install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
