# Generated by Django 5.2 on 2025-08-08 14:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='category_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
