# Generated by Django 5.2 on 2025-08-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillcategory_category_icon_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
