# Generated by Django 5.2 on 2025-08-05 12:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_alter_experience_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutus_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
