# Generated by Django 5.2 on 2025-08-05 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_alter_aboutus_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutus_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
