# Generated by Django 5.2 on 2025-08-05 17:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_alter_aboutus_aboutus_image_alter_aboutus_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutus_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutus_images'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_images'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resumes'),
        ),
    ]
