# Generated by Django 5.2 on 2025-08-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_alter_aboutus_resume_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=20)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='aboutus.aboutus')),
            ],
        ),
    ]
