# Generated by Django 5.2 on 2025-08-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
