# Generated by Django 5.2 on 2025-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_category_image_category_category_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_images',
            new_name='category_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
