# Generated by Django 5.2 on 2025-08-14 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithus', '0004_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='requirement_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
