# Generated by Django 5.2 on 2025-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithus', '0005_remove_chatsession_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
