# Generated by Django 5.2 on 2025-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithus', '0006_chatsession_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='meeting_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='platform_selected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
